spring.application.name=essentia
spring.mongodb.uri=mongodb://localhost:27017/essentia
server.port=8080
spring.jackson.deserialization.fail-on-unknown-properties=false
server.error.include-message=always
logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.messaging.simp=TRACE
logging.level.org.springframework.messaging=TRACE
